// https://lt.wiktionary.org/wiki/S%C4%85ra%C5%A1as:Da%C5%BEniausi_lietuvi%C5%A1ki_%C5%BEod%C5%BEiai
const zodziai = [
    "IR",
    "JIS",
    "BŪTI",
    "TAS",
    "Į",
    "KAD",
    "AŠ",
    "KURIS",
    "SU",
    "ŠIS",
    "GALĖTI",
    "O",
    "IŠ",
    "KAIP",
    "DARBAS",
    "AR",
    "KITAS",
    "TURĖTI",
    "VISAS",
    "ŽMOGUS",
    "LIETUVA",
    "KAS",
    "VIENAS",
    "TIK",
    "SAVO",
    "NUO",
    "TOKS",
    "BET",
    "NE",
    "APIE",
    "JAU",
    "LABAI",
    "METAI",
    "DAR",
    "DAUG",
    "TU",
    "UŽ",
    "BEI",
    "ARBA",
    "LAIKAS",
    "KAI",
    "TAIP",
    "PATS",
    "REIKĖTI",
    "PER",
    "PO",
    "NEBŪTI",
    "ČIA",
    "DĖL",
    "PRIE",
    "TAČIAU",
    "DIDELIS",
    "SISTEMA",
    "GAMYBA",
    "ĮMONĖ",
    "PIRMAS",
    "NES",
    "VIETA",
    "ŽEMĖ",
    "NORĖTI",
    "NAUJAS",
    "DABAR",
    "JEI",
    "KOKS",
    "ŽINOTI",
    "PAGAL",
    "ĮSTATYMAS",
    "VAIKAS",
    "TODĖL",
    "NET",
    "IKI",
    "GYVENIMAS",
    "NARYS",
    "DU",
    "PIRMININKAS",
    "SVARBUS",
    "ANT",
    "GRUPĖ",
    "TOMAS",
    "KIEKVIENAS",
    "DALIS",
    "ATLIKTI",
    "SEIMAS",
    "DIENA",
    "TAI",
    "SAKYTI",
    "VALSTYBĖ",
    "DUOMUO",
    "GERAI",
    "PRIEŠ",
    "KUR",
    "NEGALĖTI",
    "DAŽNAI",
    "JEIGU",
    "PASAULIS",
    "NIEKAS",
    "SUDARYTI",
    "ŠALIS",
    "KLAUSIMAS",
    "GERAS",
    "NEI",
    "NUSTATYTI",
    "BE",
    "METAS",
    "SAVĘS",
    "VISKAS",
    "PRADĖTI",
    "PROCESAS",
    "TADA",
    "KARTAS",
    "KIEK",
    "PRIIMTI",
    "GAUTI",
    "VEIKLA",
    "ŪKIS",
    "VANDUO",
    "ĮVAIRUS",
    "DIRBTI",
    "GAL",
    "VILNIUS",
    "PAGRINDINIS",
    "PATEIKTI",
    "PAVYZDYS",
    "IMTI",
    "SKIRTI",
    "INFORMACIJA",
    "LIETUVIS",
    "LIGONIS",
    "TARP",
    "RANKA",
    "TAPTI",
    "DIEVAS",
    "BENDRAS",
    "VYRIAUSYBĖ",
    "PRIEMONĖ",
    "KALBĖTI",
    "MIESTAS",
    "ŽODIS",
    "PROJEKTAS",
    "RESPUBLIKA",
    "KALBA",
    "DARYTI",
    "BENAS",
    "KULTŪRA",
    "SĄLYGA",
    "PADĖTI",
    "MAŽAS",
    "PASAKYTI",
    "ANTRAS",
    "AUKŠTAS",
    "VISAI",
    "NAUDOTI",
    "EUROPA",
    "GYVENTI",
    "NORS",
    "MANO",
    "ATRODYTI",
    "VĖL",
    "MATYTI",
    "JOG",
    "MEDŽIAGA",
    "GERBTI",
    "BŪDAS",
    "SENAS",
    "KAUNAS",
    "MANYTI",
    "VALDYMAS",
    "TEN",
    "TYRIMAS",
    "NETURĖTI",
    "MOKSLAS",
    "SPRENDIMAS",
    "ŠITAS",
    "KELI",
    "DARBUOTOJAS",
    "OPERACIJA",
    "PRIKLAUSYTI",
    "KNYGA",
    "VADINTI",
    "LAIKYTI",
    "YPAČ",
    "SUPRASTI",
    "PROBLEMA",
    "TIKSLAS",
    "ASMUO",
    "FORMA",
    "GALVA",
    "SUNKUS",
    "ATVEJIS",
    "METODAS",
    "SKYRIUS",
    "DAUGELIS",
    "EITI",
    "LEISTI",
    "MOTERIS",
    "STRAIPSNIS",
    "PADARYTI",
    "LIKTI",
    "TOLI",
    "AKIS",
    "TIKRAI",
    "VYRAS",
    "ISTORIJA",
    "LIGA",
    "ORGANIZACIJA",
    "TRYS",
    "DALYKAS",
    "VOKIETIJA",
    "VĖLAI",
    "PUSĖ",
    "MĖNUO",
    "KARTU",
    "STRUKTŪRA",
    "CENTRAS",
    "VEIKTI",
    "GAMINYS",
    "TEISĖ",
    "JUK",
    "NUMATYTI",
    "TAIGI",
    "VADOVAS",
    "LYGIS",
    "JOKS",
    "TURTAS",
    "GALIMYBĖ",
    "OBJEKTAS",
    "RINKA",
    "BEVEIK",
    "SIEKTI",
    "REZULTATAS",
    "VISIŠKAI",
    "TAUTA",
    "TECHNOLOGIJA",
    "PAGRINDAS",
    "MINISTERIJA",
    "SRITIS",
    "ŠLAITAS",
    "GREITAI",
    "ŠEIMA",
    "DOKUMENTAS",
    "MAŽAI",
    "TVARKA",
    "SIŪLYTI",
    "ATSIRASTI",
    "TIEK",
    "RYŠYS",
    "MOKYKLA",
    "TEKTI",
    "SOCIALINIS",
    "ATSKIRAS",
    "KOKYBĖ",
    "KOMITETAS",
    "PRADŽIA",
    "SANTYKIS",
    "NORMA",
    "RAŠYTI",
    "PROGRAMA",
    "MOKESTIS",
    "EKONOMINIS",
    "SKAIČIUS",
    "VYKTI",
    "MINTIS",
    "VIS",
    "JĖGA",
    "REIKALAS",
    "VARDAS",
    "BANKAS",
    "ŠIRDIS",
    "LYG",
    "POREIKIS",
    "KONTROLĖ",
    "KARTAIS",
    "TECHNINIS",
    "KELIAS",
    "PASIEKTI",
    "RASTI",
    "VAKARAI",
    "SUKURTI",
    "FONDAS",
    "KRAŠTAS",
    "ORGANIZAVIMAS",
    "NURODYTI",
    "PRITARTI",
    "ABU",
    "REIKALINGAS",
    "PALIKTI",
    "PRIEŽASTIS",
    "AMŽIUS",
    "PRAŠOM",
    "KŪNAS",
    "PAPRASTAI",
    "FUNKCIJA",
    "UOLIENA",
    "PASKUTINIS",
    "ĮRENGIMAS",
    "NAMAI",
    "PRINCIPAS",
    "KOLEGA",
    "BALSAS",
    "BAIGTI",
    "GRĮŽTI",
    "KURTI",
    "UŽSIENIS",
    "ATEITI",
    "ŠIANDIEN",
    "LITAS",
    "LATVIS",
    "GAMTA",
    "RAJONAS",
    "PINIGAS",
    "PONAS",
    "BALTAS",
    "KODĖL",
    "TEIKTI",
    "NUOMONĖ",
    "PANAŠUS",
    "TIKRAS",
    "ILGAS",
    "ATITIKTI",
    "PRAŠYTI",
    "TAIKYTI",
    "DIDIS",
    "DĖMESYS",
    "PRAEITI",
    "ELEMENTAS",
    "VAIDMUO",
    "PAS",
    "TEIGTI",
    "AIŠKUS",
    "PRO",
    "LINIJA",
    "REGISTRAS",
    "TIESA",
    "DUOTI",
    "MINISTRAS",
    "ŠTAI",
    "REIKALAVIMAS",
    "KOJA",
    "NEGU",
    "SPRĘSTI",
    "PASIRODYTI",
    "TĖVAS",
    "BAŽNYČIA",
    "SITUACIJA",
    "VOKIETIS",
    "DARBININKAS",
    "TIKTI",
    "ANKSTI",
    "LAUKTI",
    "KAIMAS",
    "PREKĖ",
    "INFORMACINIS",
    "PRODUKCIJA",
    "NUTARIMAS",
    "TARNYBA",
    "VALSTYBINIS",
    "JŪRA",
    "MINĖTI",
    "TARSI",
    "LAISVĖ",
    "PAKEISTI",
    "PLANAS",
    "VEIKSMAS",
    "DALYVAUTI",
    "GYVENTOJAS",
    "VISUOMENĖ",
    "PARDAVIMAS",
    "DURYS",
    "PATAISA",
    "NEŽINOTI",
    "PASKUI",
    "VEIDAS",
    "KOL",
    "SAVAS",
    "PRASMĖ",
    "SUTIKTI",
    "PABAIGA",
    "IEŠKOTI",
    "BENDROVĖ",
    "ORGANIZUOTI",
    "DETALĖ",
    "KADANGI",
    "SIENA",
    "VALANDA",
    "ŽIŪRĖTI",
    "RYTAI",
    "ĮVERTINTI",
    "PRAMONĖ",
    "SUTEIKTI",
    "VOS",
    "MOKĖTI",
    "VARTOTOJAS",
    "KILTI",
    "RODYTI",
    "TAVO",
    "KONKRETUS",
    "VYKDYTI",
    "PARENGTI",
    "KARAS",
    "TERITORIJA",
    "NA",
    "RYTAS",
    "SPECIALUS",
    "TIPAS",
    "ŠALTINIS",
    "JAUSMAS",
    "AUTORIUS",
    "JAUNAS",
    "MEDICINA",
    "FIRMA",
    "ILGAI",
    "GANA",
    "PASTARAS",
    "PAVADINIMAS",
    "ĮRANKIS",
    "LĖŠOS",
    "ATSAKYTI",
    "AČIŪ",
    "REMONTAS",
    "PRIVALĖTI",
    "SAVAITĖ",
    "IŠEITI",
    "KAINA",
    "TAD",
    "DYDIS",
    "KELETAS",
    "PAPILDYTI",
    "UNIVERSITETAS",
    "GYDYTOJAS",
    "PARODYTI",
    "PRASIDĖTI",
    "PREZIDENTAS",
    "MIŠKAS",
    "ANALIZĖ",
    "ESTAS",
    "PUNKTAS",
    "VISADA",
    "GALAS",
    "KITOKS",
    "MIRTIS",
    "LIGONINĖ",
    "TĖVAI",
    "JAV",
    "DAIKTAS",
    "NEREIKĖTI",
    "LAISVAS",
    "STENGTIS",
    "IŠSKIRTI",
    "SĄJUNGA",
    "TREČIAS",
    "KADA",
    "KAŽKAS",
    "KELTI",
    "ORAS",
    "MEILĖ",
    "POŽIŪRIS",
    "BAZĖ",
    "SAVIVALDYBĖ",
    "TEISMAS",
    "VAKARAS",
    "BALSUOTI",
    "REIKŠTI",
    "ŠIAURĖ",
    "BŪDINGAS",
    "SVEIKATA",
    "TARYBA",
    "VEIKSNYS",
    "ŠVIESA",
    "GAMINTI",
    "PATVIRTINTI",
    "IŠLAIDOS",
    "VADOVAUTI",
    "ĮSTAIGA",
    "ĮTAKA",
    "UŽDUOTIS",
    "VADINTIS",
    "VALDŽIA",
    "ASMENYBĖ",
    "MEDIS",
    "INSTITUCIJA",
    "KRAUJAS",
    "UŽDAVINYS",
    "VERTINTI",
    "APSKAIČIUOTI",
    "VIDUS",
    "MOKSLINIS",
    "STATYBA",
    "SUKELTI",
    "NUOŠLIAUŽA",
    "PAPRASTAS",
    "REIKŠMĖ",
    "APSAUGA",
    "AUTOMOBILIS",
    "MIRTI",
    "SŪNUS",
    "APLINKA",
    "NAKTIS",
    "PASTEBĖTI",
    "TIRTI",
    "GALBŪT",
    "LEMTI",
    "VARTOTI",
    "KLAIPĖDA",
    "ATSTOVAS",
    "DAINA",
    "MAŠINA",
    "PLANAVIMAS",
    "MATYT",
    "TIKĖTIS",
    "ŽUVIS",
    "MENAS",
    "PADĖTIS",
    "SPECIALISTAS",
    "PASIRINKTI",
    "VARIANTAS",
    "KUO",
    "ARTIMAS",
    "DVASIA",
    "LITERATŪRA",
    "PAGALBA",
    "REMTI",
    "IDĖJA",
    "ETAPAS",
    "KETURI",
    "REIKALAUTI",
    "BIUDŽETAS",
    "KŪRINYS",
    "PLOTAS",
    "SAULĖ",
    "LAUKAS",
    "SKIRTINGAS",
    "KOMANDA",
    "ĮRANGA",
    "NORAS",
    "SĄVOKA",
    "BLOGIS",
    "CECHAS",
    "NEDIDELIS",
    "RŪŠIS",
    "SCHEMA",
    "BALTIJA",
    "TRUKMĖ",
    "VAISTAS",
    "FIZINIS",
    "EKONOMIKA",
    "ELGESYS",
    "KOMPIUTERIS",
    "SPALVA",
    "VYRESNIS",
    "VIDINIS",
    "STAIGA",
    "STOVĖTI",
    "TEORIJA",
    "ATSIŽVELGTI",
    "KAMBARYS",
    "NENORĖTI",
    "ĮVYKIS",
    "APIBŪDINTI",
    "SIRGTI",
    "TINKLAS",
    "ZONA",
    "ĮVYKTI",
    "PARTIJA",
    "SRAUTAS",
    "BROLIS",
    "JAUSTI",
    "PARUOŠTI",
    "GRAŽUS",
    "RIBA",
    "AMERIKA",
    "JUODAS",
    "PADALINYS",
    "PANAUDOTI",
    "SAVYBĖ",
    "VIENETAS",
    "ATEITIS",
    "DAUGUMA",
    "IRGI",
    "PRISIMINTI",
    "TECHNIKA",
    "APSKAITA",
    "TRANSPORTAS",
    "VALIA",
    "SKAITYTI",
    "SUVOKTI",
    "KITAIP",
    "GATVĖ",
    "PRIPAŽINTI",
    "TŪKSTANTIS",
    "ŽINIOS",
    "KRYPTIS",
    "LANGAS",
    "NĖ",
    "ODA",
    "PROTAS",
    "KALNAS",
    "PASLAUGA",
    "INSTITUTAS",
    "MOTINA",
    "SUTARTIS",
    "VADYBA",
    "VERTĖ",
    "BANDYTI",
    "SUNKIAI",
    "KEISTI",
    "NAMAS",
    "RODIKLIS",
    "VALDYTI",
    "APIMTIS",
    "PAGALIAU",
    "SALĖ",
    "DIREKTORIUS",
    "KONTROLIUOTI",
    "TARTI",
    "TURINYS",
    "ESMĖ",
    "LAIKOTARPIS",
    "PARAŠYTI",
    "POBŪDIS",
    "ORGANIZACINIS",
    "TIESIOG",
    "RENGTI",
    "TARPTAUTINIS",
    "BLOGAS",
    "PLAČIAI",
    "STIPRUS",
    "KIEKIS",
    "KULTAS",
    "ENERGIJA",
    "GALVOTI",
    "GAMYBINIS",
    "MAISTAS",
    "MINUTĖ",
    "NUOLAT",
    "PATIRTI",
    "STEBĖTI",
    "SUDĖTINGAS",
    "LATVIJA",
    "AKMUO",
    "LAIDAS",
    "ĮDOMUS",
    "AKTAS",
    "PAGAMINTI",
    "ŽMONA",
    "LENGVAS",
    "IŠLEISTI",
    "IŠORINIS",
    "PRODUKTAS",
    "VERSLAS",
    "GYVAS",
    "MUZIKA",
    "PAUKŠTIS",
    "PAVIRŠIUS",
    "BŪKLĖ",
    "NETGI",
    "PAMATYTI",
    "PATEKTI",
    "PRIMINTI",
    "TAISYKLĖ",
    "CIKLAS",
    "STALAS",
    "APSKRITAI",
    "ATSAKOMYBĖ",
    "DRAUGIJA",
    "BŪTENT",
    "GEROKAI",
    "KONFLIKTAS",
    "KŪRYBA",
    "KOMISIJA",
    "UPĖ",
    "PARDUOTI",
    "PASTATAS",
    "SVARSTYTI",
    "LENKIJA",
    "PAAIŠKINTI",
    "SUJUNGTI",
    "ŽAISTI",
    "MOKYTOJAS",
    "PAŽINTI",
    "APIMTI",
    "APRAŠYTI",
    "DEJA",
    "PIENAS",
    "RUNGTYNĖS",
    "SAUGOTI",
    "ESTIJA",
    "NAGRINĖTI",
    "PATALPA",
    "RAŠYTOJAS",
    "TVIRTINTI",
    "VIENINTELIS",
    "BEJE",
    "POLICIJA",
    "APTARNAVIMAS",
    "ATVYKTI",
    "JUDESYS",
    "ŽENKLAS",
    "BYLA",
    "LIEPA",
    "PARAMA",
    "UŽMOKESTIS",
    "VASARA",
    "AIŠKIAI",
    "PRIĖMIMAS",
    "SĖDĖTI",
    "BENDRAVIMAS",
    "GIRDĖTI",
    "REIŠKINYS",
    "TUOMET",
    "RYGA",
    "LOVA",
    "POETAS",
    "POSĖDIS",
    "SESUO",
    "VERTINIMAS",
    "VERTYBĖ",
    "PAŽYMĖTI",
    "PROCENTAS",
    "BENT",
    "GRANDINĖ",
    "PASAKA",
    "PERDUOTI",
    "PIRKTI",
    "PRANEŠĖJAS",
    "UŽIMTI",
    "VYTAUTAS",
    "PLATUS",
    "SENIAI",
    "ATSISAKYTI",
    "MOKSLININKAS",
    "MOTYVAS",
    "STUDENTAS",
    "TIRPALAS",
    "DRAUDIMAS",
    "FILOSOFIJA",
    "KŪRIMAS",
    "PIETŪS",
    "TIKSLIAI",
    "ĮGYVENDINTI",
    "ASMENINIS",
    "BAIGTIS",
    "GIMTI",
    "PASKIRTI",
    "POLITIKA",
    "PROJEKTAVIMAS",
    "ATSAKYMAS",
    "FINANSAI",
    "MODELIS",
    "PALYGINTI",
    "PATENKINTI",
    "SKIRTIS",
    "STAMBUS",
    "TAM",
    "TARPUSAVIS",
    "DRAUGAS",
    "ISTORINIS",
    "IŠKILTI",
    "PAKEITIMAS",
    "PROCEDŪRA",
    "APTARTI",
    "EKSPERTAS",
    "NAUDOJIMAS",
    "LENTELĖ",
    "LIZDAS",
    "NEMATYTI",
    "IŠDUOTI",
    "PAJAMOS",
    "SURINKTI",
    "KOVA",
    "VAIZDAS",
    "DOLERIS",
    "KLASĖ",
    "PAGALBINIS",
    "PASIŪLYMAS",
    "POŽYMIS",
    "PREKYBA",
    "TAMSUS",
    "AUGTI",
    "GI",
    "NUOSTATA",
    "PASKELBTI",
    "SIELA",
    "SKATINTI",
    "IŠVADA",
    "PARTNERIS",
    "TRUMPAS",
    "BENDRAUTI",
    "LENGVAS",
    "PIRŠTAS",
    "TIKTAI",
    "ĮRAŠYTI",
    "BRANGUS",
    "PASAULINIS",
    "PILIS",
    "SPAUDA",
    "SUSIDARYTI",
    "TAUTINIS",
    "TIKĖTI",
    "JONAS",
    "KOMPLEKSAS",
    "SKAUSMAS",
    "KAPITALAS",
    "PAIMTI",
    "PAVADINTI",
    "SVETIMAS",
    "KIEK",
    "GYDYMAS",
    "ORGANAS",
    "RAŠTAS",
    "TIKĖJIMAS",
    "ALEKSANDRAS",
    "GRAFIKAS",
    "LAPAS",
    "PORA",
    "TURBŪT",
    "ANAS",
    "DRABUŽIS",
    "GYVULYS",
    "IŠLIKTI",
    "LAIKYTIS",
    "NUMERIS",
    "SANDĖLIS",
    "SVEČIAS",
    "TEKSTAS",
    "ŠALIA",
    "AIŠKINTI",
    "DALYVIS",
    "VISTIEK",
    "KELIONĖ",
    "ŽINGSNIS",
    "PASIDARYTI",
    "POVEIKIS",
    "RAUDONAS",
    "ŠAKA",
    "ŠALTAS",
    "ŪKININKAS",
    "INDIVIDUALUS",
    "LIETUVIŠKAS",
    "MAMA",
    "PEREITI",
    "SROVINIS",
    "TRADICIJA",
    "DIRBINYS",
    "PAREIGŪNAS",
    "SUSIPAŽINTI",
    "VIDUTINIS",
    "ŽAIDIMAS",
    "EGZISTUOTI",
    "IŠMOKTI",
    "KLAIDA",
    "PASKOLA",
    "PENKI",
    "PRARASTI",
    "PRISKIRTI",
    "RIMTAS",
    "TEMPERATŪRA",
    "TERMINAS",
    "VIDURYS",
    "MĖGINTI",
    "NUTARTI",
    "PAGALVOTI",
    "PAKANKAMAI",
    "PRAKTIKA",
    "SUOMIS",
    "UŽTIKRINTI",
    "VIENETINIS",
    "ATVIRAS",
    "DIDŽIULIS",
    "PASIŪLYTI",
    "RŪMAI",
    "ŽVILGSNIS",
    "LAIVAS",
    "PALAIKYTI",
    "PIRMINIS",
    "PRIETAISAS",
    "TAMSA",
    "DEŠIMTMETIS",
    "PATIRTIS",
    "VAKAR",
    "PRANCŪZIJA",
    "BAIMĖ",
    "DVASINIS",
    "ELEKTRA",
    "PARA",
    "SUDĖTIS",
    "ŠITAIP",
    "ESMĖ",
    "KALTĖ",
    "KAMPAS",
    "KREIPTIS",
    "LIAUDIS",
    "MOKYTIS",
    "PASKIRTIS",
    "PASTATYTI",
    "PELNAS",
    "REMTIS",
    "STAKLĖS",
    "SVEIKAS",
    "SĄRAŠAS",
    "APSKRITIS",
    "KOMPIUTERIZUOTI",
    "PASIKEISTI",
    "SANDARA",
    "STADIJA",
    "VASARIS",
    "EILĖRAŠTIS",
    "INTERESAS",
    "KAŽKOKS",
    "KUNIGAIKŠTIS",
    "PASAKOTI",
    "SKAIČIAVIMAS",
    "DABARTINIS",
    "DAUGIAUSIA",
    "KLUBAS",
    "MOKYMAS",
    "PRADAS",
    "SUMAŽĖTI",
    "TAŠKAS",
    "VISATA",
    "ŠVIETIMAS",
    "ŽIEMA",
    "IMTIS",
    "IŠREIKŠTI",
    "MĖGTI",
    "PADIDĖTI",
    "PAMAŽU",
    "SMULKUS",
    "AKCINIS",
    "PRAEITIS",
    "ĮSIVAIZDUOTI",
    "DANGUS",
    "ELGTIS",
    "INDAS",
    "KILMĖ",
    "KOEFICIENTAS",
    "RAIDA",
    "SPORTAS",
    "VILKAS",
    "SOKRATAS",
    "KODAS",
    "KONCEPCIJA",
    "PABRĖŽTI",
    "REALUS",
    "STATYTI",
    "SUBJEKTAS",
    "TAURĖ",
    "TEMA",
    "ATSARGA",
];

var isrinktasZodis = "";
var atsakymas = "";
var klaiduSkaicius = 0;
var raidziuMygtukai = document.getElementsByClassName("raides-mygtukas");

generuokZodi();

function generuokZodi()
{
    var a = Math.floor(Math.random()*zodziai.length);
    isrinktasZodis = zodziai[a];

    klaiduSkaicius = 0;
    baigesiZaidimas = false;
    document.getElementById("klaidos").innerHTML = "Klaidų skaičius: " + klaiduSkaicius;
    document.getElementById("rezultatas").innerHTML = "";
    document.getElementById("kartuves").innerHTML = "";

    for (var i=0; i<raidziuMygtukai.length; i++)
    {
        raidziuMygtukai[i].classList.remove("nera");
        raidziuMygtukai[i].classList.remove("yra");
        raidziuMygtukai[i].disabled = false;
    }

    atsakymas = "";
    for(var i=0; i<isrinktasZodis.length; i++)
    {
        atsakymas = atsakymas + "_";
    }

    document.getElementById("zodis").innerHTML = atsakymas;
}

var hangmanpics = [`
  +---+
      |
      |
      |
      |
      |
=========`, `
  +---+
  |   |
      |
      |
      |
      |
=========`, `
  +---+
  |   |
  O   |
      |
      |
      |
=========`, `
  +---+
  |   |
  O   |
  |   |
      |
      |
=========`, `
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========`, `
  +---+
  |   |
  O   |
 /|\\  |
      |
      |
=========`, `
  +---+
  |   |
  O   |
 /|\\  |
 /    |
      |
=========`, `
  +---+
  |   |
  O   |
 /|\\  |
 / \\  |
      |
=========`];

var maxKlaiduSkaicius = 8;
var baigesiZaidimas = false;


for (var i=0; i<raidziuMygtukai.length; i++)
{
    raidziuMygtukai[i].addEventListener('click', (event) =>
    {
        if(baigesiZaidimas)
        {
            return;
        }
        
        event.target.disabled = true;

        var raide = event.target.innerHTML;
        var bentVienaTiko = false;

        

        for(var i=0; i<isrinktasZodis.length; i++)
        {
            if(isrinktasZodis[i] == raide && klaiduSkaicius < maxKlaiduSkaicius)
            {
                atsakymas = atsakymas.substring(0, i) + raide + atsakymas.substring(i + 1);
                console.log('pataike', raide, atsakymas, isrinktasZodis);
                document.getElementById("zodis").innerHTML = atsakymas;
                bentVienaTiko = true;
            }
        }

        

        if(!bentVienaTiko && klaiduSkaicius <= maxKlaiduSkaicius)
        {
            if(klaiduSkaicius < maxKlaiduSkaicius)
            {
                event.target.classList.add("nera");
                klaiduSkaicius++;
            }

            document.getElementById("klaidos").innerHTML = "Klaidų skaičius: " + klaiduSkaicius;

            if(klaiduSkaicius >= maxKlaiduSkaicius)
            {
                document.getElementById("rezultatas").innerHTML = "Pralaimėjai, bandyk dar kartą!";
                
                baigesiZaidimas = true;

                var atsakymasSuKlaidomis = "";
                
                for(var i=0; i<isrinktasZodis.length; i++)
                {
                    if(atsakymas[i] == "_")
                    {
                        atsakymasSuKlaidomis = atsakymasSuKlaidomis + '<span class="neatspeta-raide">' + isrinktasZodis[i] + '</span>';
                        //atsakymas = atsakymas.substring(0, i) + '<span class="neatspeta-raide">' + isrinktasZodis[i] + '</span>' + atsakymas.substring(i + 1);
                    }
                    else 
                    {
                        atsakymasSuKlaidomis = atsakymasSuKlaidomis + atsakymas[i];
                    }
                }
                document.getElementById("zodis").innerHTML = atsakymasSuKlaidomis;
            }

            document.getElementById("kartuves").innerHTML = "<pre>" + hangmanpics[klaiduSkaicius - 1] + "</pre>";

            
        }
        else if(klaiduSkaicius < maxKlaiduSkaicius)
        {
            event.target.classList.add("yra");
        }


        if(atsakymas.indexOf("_") == -1 && klaiduSkaicius<maxKlaiduSkaicius)
        {
            baigesiZaidimas = true;
            // document.getElementById("rezultatas").innerHTML = "";
            // document.getElementById("rezultatas").innerHTML = 'Laimėjai!!!<br><img src="https://media1.giphy.com/media/peAFQfg7Ol6IE/200w.gif?cid=82a1493br2a7av1k2jh5npavj6zfqxyu1fwplj19ojrssiug&rid=200w.gif&ct=g" />';
            // document.getElementById("rezultatas").innerHTML = '<img src="https://cataas.com/cat/says/Laim%C4%97jai!?' + new Date() + '" />';
            document.getElementById("rezultatas").innerHTML = '<img src="https://thecatapi.com/api/images/get?format=src&type=gif&' + new Date().getTime() + '" />';

        }

    })
}
